### ISSUE TITLE
import seqio: AttributeError: module 'typing' has no attribute 'get_origin'

### ISSUE THREAD

**Issue by PhoebusSi** [google/seqio#502]
>>> import seqio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/seqio/__init__.py", line 18, in <module>
    from seqio.dataset_providers import *
  File "/usr/local/lib/python3.7/dist-packages/seqio/dataset_providers.py", line 38, in <module>
    import pyglove as pg
  File "/usr/local/lib/python3.7/dist-packages/pyglove/__init__.py", line 30, in <module>
    from pyglove.core import *
  File "/usr/local/lib/python3.7/dist-packages/pyglove/core/__init__.py", line 56, in <module>
    from pyglove.core import symbolic
  File "/usr/local/lib/python3.7/dist-packages/pyglove/core/symbolic/__init__.py", line 93, in <module>
    from pyglove.core.symbolic.diff import diff
  File "/usr/local/lib/python3.7/dist-packages/pyglove/core/symbolic/diff.py", line 153, in <module>
    (pg_typing.StrKey(), pg_typing.Object(Diff), 'Child node.')
  File "/usr/local/lib/python3.7/dist-packages/pyglove/core/typing/value_specs.py", line 1279, in __init__
    schema_or_field_list, allow_nonconst_keys=True)
  File "/usr/local/lib/python3.7/dist-packages/pyglove/core/typing/class_schema.py", line 1179, in create_schema
    value = ValueSpec.from_annotation(maybe_value_spec, True)
  File "/usr/local/lib/python3.7/dist-packages/pyglove/core/typing/value_specs.py", line 2131, in _from_annotation
    origin = typing.get_origin(annotation)
AttributeError: module 'typing' has no attribute 'get_origin'

**Comment by gauravmishra** [comment]
this is likely a python version issue. Could you make sure you're using 3.8+?
