### ISSUE TITLE
ValueError: mutable default <class 'seqio.vocabularies.PassThroughVocabulary'> for field vocabulary is not allowed: use default_factory

### ISSUE THREAD

**Issue by jli262** [google/seqio#562]
Traceback (most recent call last):
  File "/scenic/scenic/projects/vid2seq/vid2seq_test.py", line 13, in <module>
    from scenic.projects.vid2seq import trainer
  File "/anaconda3/envs/vid2seq/lib/python3.11/site-packages/scenic/projects/vid2seq/trainer.py", line 26, in <module>
    from scenic.projects.t5 import model as t5_model
  File "/anaconda3/envs/vid2seq/lib/python3.11/site-packages/scenic/projects/t5/model.py", line 29, in <module>
    from scenic.projects.t5 import layers
  File "/anaconda3/envs/vid2seq/lib/python3.11/site-packages/scenic/projects/t5/layers.py", line 9, in <module>
    from t5x import decoding
  File "/anaconda3/envs/vid2seq/lib/python3.11/site-packages/t5x/__init__.py", line 17, in <module>
    import t5x.adafactor
  File "/anaconda3/envs/vid2seq/lib/python3.11/site-packages/t5x/adafactor.py", line 64, in <module>
    from t5x import utils
  File "/anaconda3/envs/vid2seq/lib/python3.11/site-packages/t5x/utils.py", line 44, in <module>
    import seqio
  File "/anaconda3/envs/vid2seq/lib/python3.11/site-packages/seqio/__init__.py", line 18, in <module>
    from seqio.dataset_providers import *
  File "/anaconda3/envs/vid2seq/lib/python3.11/site-packages/seqio/dataset_providers.py", line 60, in <module>
    @dataclasses.dataclass(frozen=True)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/envs/vid2seq/lib/python3.11/dataclasses.py", line 1213, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/envs/vid2seq/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/envs/vid2seq/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'seqio.vocabularies.PassThroughVocabulary'> for field vocabulary is not allowed: use default_factory

**Comment by igor17400** [comment]
I had the same error.
Did you manage to figure out @jli262 ?

**Comment by zbl94** [comment]
Same error here
